# Generated by Django 3.1.2 on 2020-12-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patient.base')),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=999, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='image.jpeg', null=True, upload_to='')),
                ('verification', models.BooleanField(default=False)),
                ('trustedContact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            bases=('patient.base',),
        ),
    ]
